### ISSUE TITLE
Variable AirCrashlytics is not defined

### ISSUE THREAD

**Issue by andrievsky** [freshplanet/ANE-Crashlytics#20]
Thank you for building great ANE's.

I forced with the issue trying to add the extension to my app. I'm building it with Intellij Idea. 

There's the log:

"/Applications/IntelliJ IDEA.app/Contents/jre/jdk/Contents/Home/jre/bin/java" -Dapplication.home=/Users/nick/master/sdk/AIRSDK_Compiler_22 -Dfile.encoding=UTF-8 -Djava.awt.headless=true -Duser.language=en -Duser.region=en -Xmx512m -classpath /Users/nick/master/sdk/AIRSDK_Compiler_22/lib/legacy/fdb.jar flex.tools.debugger.cli.DebugCLI -p 7936…
Adobe fdb (Flash Player Debugger) [build development]
Copyright (c) 2004-2007 Adobe, Inc. All rights reserved.
Trying to connect to Player
Player connected; session starting.
[trace] [Starling] Context ready. Display Driver: OpenGL (Baseline Extended)
java.lang.ArrayIndexOutOfBoundsException: -2
	at flash.tools.debugger.concrete.ScriptText.getLine(ScriptText.java:38)
	at flash.tools.debugger.concrete.DModule.getLine(DModule.java:135)
	at flex.tools.debugger.cli.DebugCLI.dumpBreakLine(DebugCLI.java:2485)
	at flex.tools.debugger.cli.DebugCLI.dumpHaltState(DebugCLI.java:2289)
	at flex.tools.debugger.cli.DebugCLI.runningLoop(DebugCLI.java:2821)
	at flex.tools.debugger.cli.DebugCLI.process(DebugCLI.java:817)
	at flex.tools.debugger.cli.DebugCLI.execute(DebugCLI.java:669)
	at flex.tools.debugger.cli.DebugCLI.main(DebugCLI.java:461)
[Fault] exception, information=ReferenceError: Error #1065: Variable com.freshplanet.ane.AirCrashlytics::AirCrashlytics is not defined.

**Comment by andrievsky** [comment]
If I'm adding <extensionID>com.freshplanet.ane.AirCrashlytics</extensionID> to descriptor adt packing error occurs: "An implementation for native extension 'com.freshplanet.ane.AirCrashlytics' requared by the application was not found for the target platform"

**Comment by laraibmalik90** [comment]
please add import com.freshplanet.ane.AirCrashlytics.AirCrashlytics (as suggestions are also given by adobe IDE ). It should work

**Comment by tontonpiero** [comment]
Add this line in the <extensions> list of the app.xml file:
<extensionID>com.freshplanet.AirCrashlytics</extensionID>

**Comment by andrievsky** [comment]
Thank you for the updated. I'm afraid it's a little bit outdated for now)
